
import Main from "@/components/main/Main";
import { Inter,Nunito } from "next/font/google";
import getUser from "./actions/getUser";

import "./globals.css";


const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Leskar | Air Bnb",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user =await getUser()
  console.log(".......",user);

  return (
    <html lang="en">
      <body className={`${inter.className}    `}>
       <Main currentUser={user}/>
       <div className=" absolute top-1/2">
        {user?.user?.name?.name}
       </div>
   
        {children}
        </body>
    </html>
  );
}
