import NavBar from "../components/navbar/NavBar";
import { Inter,Nunito } from "next/font/google";
import "./globals.css";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Leskar | Air Bnb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}  `}>
        <NavBar/>
        {children}
        </body>
    </html>
  );
}
